import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { authorize } from '../../auth/authorize.js';
import { query,transaction } from '../../lib/database.js';
import { recordAudit } from '../../lib/audit.js';
import { requestCorrelationId } from '../../lib/request-context.js';

const uuid=z.string().uuid();
export async function registerUsersRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/users',async request=>{await authorize(request,'user.read');return query(`select u.id,u.email,u.display_name,u.status,u.created_at,u.updated_at,coalesce(array_agg(distinct r.key) filter(where r.key is not null),'{}') role_keys,coalesce(array_agg(distinct p.key) filter(where p.key is not null),'{}') permission_keys from app.users u left join app.user_roles ur on ur.user_id=u.id left join app.roles r on r.id=ur.role_id left join app.role_permissions rp on rp.role_id=r.id left join app.permissions p on p.id=rp.permission_id group by u.id order by u.display_name,u.email`)});
  app.get('/v1/roles',async request=>{await authorize(request,'user.read');return query(`select r.*,coalesce(array_agg(p.key order by p.key) filter(where p.key is not null),'{}') permission_keys from app.roles r left join app.role_permissions rp on rp.role_id=r.id left join app.permissions p on p.id=rp.permission_id group by r.id order by r.system desc,r.name`)});
  app.get('/v1/permissions',async request=>{await authorize(request,'role.manage');return query(`select * from app.permissions order by key`)});

  app.post('/v1/roles',async(request,reply)=>{const user=await authorize(request,'role.manage');const body=z.object({key:z.string().regex(/^[a-z0-9_.-]+$/).max(100),name:z.string().min(1).max(150),description:z.string().max(1000).nullable().optional(),permissionKeys:z.array(z.string()).max(200).default([])}).parse(request.body);const cid=requestCorrelationId(request);const result=await transaction(async client=>{const role=await client.query<{id:string}>(`insert into app.roles(key,name,description,system) values($1,$2,$3,false) returning *`,[body.key,body.name,body.description??null]);for(const key of [...new Set(body.permissionKeys)]){const permission=await client.query<{id:string}>(`select id from app.permissions where key=$1`,[key]);if(!permission.rows[0])throw Object.assign(new Error(`Unknown permission: ${key}`),{statusCode:400});await client.query(`insert into app.role_permissions(role_id,permission_id) values($1,$2)`,[role.rows[0]!.id,permission.rows[0].id])}await recordAudit(client,{actorUserId:user.id,action:'role.created',entityType:'role',entityId:role.rows[0]!.id,after:role.rows[0],correlationId:cid,metadata:{permissionKeys:body.permissionKeys}});return role.rows[0]});return reply.code(201).send(result)});

  app.put('/v1/roles/:id/permissions',async request=>{const user=await authorize(request,'role.manage');const id=uuid.parse((request.params as{id:string}).id);const body=z.object({permissionKeys:z.array(z.string()).max(200)}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{const role=await client.query<{key:string;system:boolean}>(`select key,system from app.roles where id=$1 for update`,[id]);if(!role.rows[0])throw Object.assign(new Error('Role not found'),{statusCode:404});if(role.rows[0].key==='owner')throw Object.assign(new Error('Owner permissions are protected'),{statusCode:409});const before=await client.query(`select p.key from app.role_permissions rp join app.permissions p on p.id=rp.permission_id where rp.role_id=$1`,[id]);await client.query(`delete from app.role_permissions where role_id=$1`,[id]);for(const key of [...new Set(body.permissionKeys)]){const permission=await client.query<{id:string}>(`select id from app.permissions where key=$1`,[key]);if(!permission.rows[0])throw Object.assign(new Error(`Unknown permission: ${key}`),{statusCode:400});await client.query(`insert into app.role_permissions(role_id,permission_id) values($1,$2)`,[id,permission.rows[0].id])}await recordAudit(client,{actorUserId:user.id,action:'role.permissions.updated',entityType:'role',entityId:id,before:before.rows,after:body.permissionKeys,correlationId:cid});return{roleId:id,permissionKeys:body.permissionKeys}})});

  app.put('/v1/users/:id/roles',async request=>{const user=await authorize(request,'user.manage');await authorize(request,'role.manage');const id=uuid.parse((request.params as{id:string}).id);const body=z.object({roleKeys:z.array(z.string()).max(30)}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{const target=await client.query(`select id,email from app.users where id=$1 for update`,[id]);if(!target.rows[0])throw Object.assign(new Error('User not found'),{statusCode:404});const before=await client.query<{key:string}>(`select r.key from app.user_roles ur join app.roles r on r.id=ur.role_id where ur.user_id=$1`,[id]);const hadOwner=before.rows.some(row=>row.key==='owner');const keepsOwner=body.roleKeys.includes('owner');if(hadOwner&&!keepsOwner){const owners=await client.query<{count:string}>(`select count(distinct ur.user_id)::text count from app.user_roles ur join app.roles r on r.id=ur.role_id join app.users u on u.id=ur.user_id where r.key='owner' and u.status='active'`);if(Number(owners.rows[0]?.count??0)<=1)throw Object.assign(new Error('The last active owner cannot be removed'),{statusCode:409})}await client.query(`delete from app.user_roles where user_id=$1`,[id]);for(const key of [...new Set(body.roleKeys)]){const role=await client.query<{id:string}>(`select id from app.roles where key=$1`,[key]);if(!role.rows[0])throw Object.assign(new Error(`Unknown role: ${key}`),{statusCode:400});await client.query(`insert into app.user_roles(user_id,role_id,assigned_by) values($1,$2,$3)`,[id,role.rows[0].id,user.id])}await recordAudit(client,{actorUserId:user.id,action:'user.roles.updated',entityType:'user',entityId:id,before:before.rows.map(row=>row.key),after:body.roleKeys,correlationId:cid});return{userId:id,roleKeys:body.roleKeys}})});

  app.patch('/v1/users/:id/status',async request=>{const user=await authorize(request,'user.manage');const id=uuid.parse((request.params as{id:string}).id);const body=z.object({status:z.enum(['active','disabled'])}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{const current=await client.query<{status:string}>(`select status from app.users where id=$1 for update`,[id]);if(!current.rows[0])throw Object.assign(new Error('User not found'),{statusCode:404});if(body.status==='disabled'){const owner=await client.query(`select 1 from app.user_roles ur join app.roles r on r.id=ur.role_id where ur.user_id=$1 and r.key='owner'`,[id]);if(owner.rows[0]){const owners=await client.query<{count:string}>(`select count(distinct ur.user_id)::text count from app.user_roles ur join app.roles r on r.id=ur.role_id join app.users u on u.id=ur.user_id where r.key='owner' and u.status='active'`);if(Number(owners.rows[0]?.count??0)<=1)throw Object.assign(new Error('The last active owner cannot be disabled'),{statusCode:409})}}const saved=await client.query(`update app.users set status=$2,updated_at=now() where id=$1 returning id,email,display_name,status`,[id,body.status]);await recordAudit(client,{actorUserId:user.id,action:'user.status.updated',entityType:'user',entityId:id,before:current.rows[0],after:saved.rows[0],correlationId:cid});return saved.rows[0]})});
}
