'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { PROVIDER_CAPABILITIES, type IntegrationProviderKey } from '@carlog/integrations';
import { apiRequest } from '../../lib/api';
import { useAuth } from '../auth/auth-provider';

type Connection={id:string;provider:IntegrationProviderKey;account_label:string;external_account_id:string|null;status:string;secret_ref:string|null;last_sync_at:string|null;last_health_check_at:string|null;last_error_code:string|null;last_error_message:string|null;capabilities:Array<{capability:string;authorized:boolean}>};
const providerLabels:Partial<Record<IntegrationProviderKey,string>>={dialpad:'Dialpad',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',website:'Car Log Website',google_ads:'Google Ads',google_analytics_4:'Google Analytics 4',google_search_console:'Google Search Console',google_business_profile:'Google Business Profile',google_maps:'Google Maps',google_places:'Google Places',youtube:'YouTube',central_dispatch:'Central Dispatch',super_dispatch:'Super Dispatch',fmcsa:'FMCSA',nhtsa:'NHTSA',stripe:'Stripe',authorize_net:'Authorize.Net',quickbooks:'QuickBooks'};

export function IntegrationsView(){
  const {user}=useAuth();const [connections,setConnections]=useState<Connection[]>([]);const [provider,setProvider]=useState<IntegrationProviderKey>('dialpad');const [selectedCapabilities,setSelectedCapabilities]=useState<string[]>([...PROVIDER_CAPABILITIES.dialpad]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const capabilities=useMemo(()=>PROVIDER_CAPABILITIES[provider],[provider]);
  async function load(){setError('');try{setConnections(await apiRequest<Connection[]>('/v1/integrations'))}catch(reason){setError(reason instanceof Error?reason.message:'Integrations failed')}}
  useEffect(()=>{void load()},[]);
  function changeProvider(next:IntegrationProviderKey){setProvider(next);setSelectedCapabilities([...PROVIDER_CAPABILITIES[next]])}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const envName=String(form.get('secretEnv')??'').trim().toUpperCase();try{await apiRequest(`/v1/integrations/${provider}`,{method:'PUT',body:JSON.stringify({accountLabel:String(form.get('accountLabel')??'Primary').trim()||'Primary',externalAccountId:String(form.get('externalAccountId')??'').trim()||null,...(envName?{secretRef:`env:${envName}`}:{ }),requestedCapabilities:selectedCapabilities,metadata:{configuredFrom:'admin'}})});event.currentTarget.reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:'Integration save failed')}finally{setBusy(false)}}
  async function command(id:string,action:'health'|'disconnect'){setBusy(true);setError('');try{await apiRequest(`/v1/integrations/${id}/${action}`,{method:'POST'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Integration action failed')}finally{setBusy(false)}}
  const canManage=user?.permissions.includes('integration.manage');const canCredentials=user?.permissions.includes('integration.credentials.manage');
  return <main className="page"><div className="page-header"><div><h1>Integrations</h1><p>Provider connections are configured here; operational use remains inside the module that owns the workflow. A saved secret reference does not mean the provider is connected.</p></div><button className="icon-button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="error-state">{error}</div>:null}
    {canManage?<form className="panel" onSubmit={save} style={{marginBottom:18}}><div className="panel-head"><h2>Configure Provider</h2><span>Secrets stay server-side; enter an environment variable name, never the secret value.</span></div><div style={{display:'grid',gap:12,padding:16}}><div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1fr',gap:10}}><select value={provider} onChange={event=>changeProvider(event.target.value as IntegrationProviderKey)} style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}>{(Object.keys(PROVIDER_CAPABILITIES) as IntegrationProviderKey[]).map(key=><option key={key} value={key}>{providerLabels[key]??key}</option>)}</select><input name="accountLabel" placeholder="Account label (Primary)" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><input name="externalAccountId" placeholder="External account ID" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/></div>{canCredentials?<input name="secretEnv" placeholder="Environment variable, e.g. DIALPAD_ACCESS_TOKEN" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/>:<div className="notice">You can configure capabilities, but only users with integration credential permission can change secret references.</div>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{capabilities.map(capability=><label key={capability} className="badge" style={{cursor:'pointer'}}><input type="checkbox" checked={selectedCapabilities.includes(capability)} onChange={event=>setSelectedCapabilities(current=>event.target.checked?[...current,capability]:current.filter(item=>item!==capability))}/>&nbsp;{capability}</label>)}</div><button className="icon-button" disabled={busy}>Save configuration</button></div></form>:null}
    <section className="panel"><div className="panel-head"><h2>Provider Connections</h2><span>{connections.length} configured accounts</span></div>{connections.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Provider</th><th>Account</th><th>Status</th><th>Capabilities</th><th>Secret Reference</th><th>Last Error</th><th>Actions</th></tr></thead><tbody>{connections.map(connection=><tr key={connection.id}><td>{providerLabels[connection.provider]??connection.provider}</td><td>{connection.account_label}<br/><small>{connection.external_account_id??'No external ID'}</small></td><td><span className="badge" data-tone={connection.status==='connected'?'good':connection.status==='error'?'bad':'warn'}>{connection.status}</span></td><td>{connection.capabilities.map(item=><span className="badge" data-tone={item.authorized?'good':'warn'} key={item.capability} style={{margin:2}}>{item.capability}</span>)}</td><td>{connection.secret_ref??'Not configured'}</td><td>{connection.last_error_message??'—'}</td><td>{canManage?<><button className="icon-button" disabled={busy} onClick={()=>void command(connection.id,'health')}>Check</button> <button className="icon-button" disabled={busy} onClick={()=>void command(connection.id,'disconnect')}>Disconnect</button></>:null}</td></tr>)}</tbody></table></div>:<div className="empty-state">No provider connections configured.</div>}</section>
  </main>;
}
