import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { PermissionKey } from '@carlog/auth';
import { authorize } from '../../auth/authorize.js';
import { query,transaction } from '../../lib/database.js';
import { recordAudit } from '../../lib/audit.js';
import { requestCorrelationId } from '../../lib/request-context.js';

const uuid=z.string().uuid();
const jsonSchema=z.object({type:z.literal('object'),required:z.array(z.string()).optional(),properties:z.record(z.string(),z.object({type:z.enum(['string','number','boolean','object','array']),nullable:z.boolean().optional()}))});
function ensurePermissions(user:{permissions:PermissionKey[]},required:string[]):void{for(const permission of required)if(!user.permissions.includes(permission as PermissionKey))throw Object.assign(new Error(`Missing required permission: ${permission}`),{statusCode:403})}

export async function registerAiRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/ai-skills',async request=>{await authorize(request,'ai_skill.read');return query(`select s.*,coalesce(jsonb_agg(jsonb_build_object('toolKey',t.tool_key,'requiredPermission',t.required_permission)) filter(where t.tool_key is not null),'[]'::jsonb) tools from app.ai_skill_definitions s left join app.ai_skill_tools t on t.skill_id=s.id group by s.id order by s.key,s.version desc`)});
  app.get('/v1/ai-skills/executions',async request=>{await authorize(request,'ai_skill.read');return query(`select e.*,s.key,s.name from app.ai_skill_executions e join app.ai_skill_definitions s on s.id=e.skill_id order by e.started_at desc limit 500`)});

  app.post('/v1/ai-skills',async(request,reply)=>{const user=await authorize(request,'ai_skill.manage');const body=z.object({key:z.string().regex(/^[a-z0-9_.-]+$/).max(160),name:z.string().min(1).max(200),description:z.string().min(1).max(2000),category:z.string().min(1).max(100),inputSchema:jsonSchema,outputSchema:jsonSchema,instructions:z.string().min(1).max(30000),requiredPermissions:z.array(z.string().min(1).max(120)).max(50).default([]),approvalPolicy:z.enum(['manual','supervised','automatic']).default('supervised'),timeoutMs:z.number().int().min(1000).max(300000).default(30000),maxAttempts:z.number().int().min(1).max(5).default(1),tools:z.array(z.object({toolKey:z.string().min(1).max(160),requiredPermission:z.string().min(1).max(120)})).max(50).default([]),metadata:z.record(z.string(),z.unknown()).default({})}).parse(request.body);const cid=requestCorrelationId(request);const result=await transaction(async client=>{const version=await client.query<{version:number}>(`select coalesce(max(version),0)+1 as version from app.ai_skill_definitions where key=$1`,[body.key]);const created=await client.query<{id:string}>(`insert into app.ai_skill_definitions(key,name,description,category,version,status,input_schema,output_schema,instructions,required_permissions,approval_policy,timeout_ms,max_attempts,metadata,created_by) values($1,$2,$3,$4,$5,'draft',$6::jsonb,$7::jsonb,$8,$9::text[],$10,$11,$12,$13::jsonb,$14) returning *`,[body.key,body.name,body.description,body.category,version.rows[0]!.version,JSON.stringify(body.inputSchema),JSON.stringify(body.outputSchema),body.instructions,body.requiredPermissions,body.approvalPolicy,body.timeoutMs,body.maxAttempts,JSON.stringify(body.metadata),user.id]);const id=created.rows[0]!.id;for(const tool of body.tools)await client.query(`insert into app.ai_skill_tools(skill_id,tool_key,required_permission) values($1,$2,$3)`,[id,tool.toolKey,tool.requiredPermission]);await recordAudit(client,{actorUserId:user.id,action:'ai_skill.created',entityType:'ai_skill_definition',entityId:id,after:created.rows[0],correlationId:cid});return created.rows[0]});return reply.code(201).send(result)});

  app.post('/v1/ai-skills/:id/activate',async request=>{const user=await authorize(request,'ai_skill.manage');const id=uuid.parse((request.params as{id:string}).id);const cid=requestCorrelationId(request);return transaction(async client=>{const target=await client.query<{key:string}>(`select key from app.ai_skill_definitions where id=$1 for update`,[id]);if(!target.rows[0])throw Object.assign(new Error('AI skill not found'),{statusCode:404});await client.query(`update app.ai_skill_definitions set status='disabled',updated_at=now() where key=$1 and status='active' and id<>$2`,[target.rows[0].key,id]);const row=await client.query(`update app.ai_skill_definitions set status='active',updated_at=now() where id=$1 returning *`,[id]);await recordAudit(client,{actorUserId:user.id,action:'ai_skill.activated',entityType:'ai_skill_definition',entityId:id,after:row.rows[0],correlationId:cid});return row.rows[0]})});

  app.post('/v1/ai-skills/:key/execute',async(request,reply)=>{const user=await authorize(request,'ai_skill.execute');const key=z.string().min(1).max(160).parse((request.params as{key:string}).key);const body=z.object({input:z.record(z.string(),z.unknown())}).parse(request.body);const cid=requestCorrelationId(request);const result=await transaction(async client=>{const skill=await client.query<{id:string;version:number;approval_policy:'manual'|'supervised'|'automatic';required_permissions:string[]}>(`select id,version,approval_policy,required_permissions from app.ai_skill_definitions where key=$1 and status='active'`,[key]);const row=skill.rows[0];if(!row)throw Object.assign(new Error('AI skill is unavailable'),{statusCode:404});ensurePermissions(user,row.required_permissions);const status=row.approval_policy==='manual'?'pending_approval':'running';const execution=await client.query<{id:string}>(`insert into app.ai_skill_executions(skill_id,skill_version,user_id,correlation_id,status,input) values($1,$2,$3,$4,$5,$6::jsonb) returning id`,[row.id,row.version,user.id,cid,status,JSON.stringify(body.input)]);await recordAudit(client,{actorUserId:user.id,action:'ai_skill.execution.requested',entityType:'ai_skill_execution',entityId:execution.rows[0]!.id,correlationId:cid,metadata:{skillKey:key,status}});return{executionId:execution.rows[0]!.id,status}});return reply.code(202).send(result)});

  app.post('/v1/ai-skills/executions/:id/approve',async request=>{const user=await authorize(request,'ai_skill.execute');const id=uuid.parse((request.params as{id:string}).id);const cid=requestCorrelationId(request);return transaction(async client=>{const execution=await client.query<{status:string;required_permissions:string[]}>(`select e.status,s.required_permissions from app.ai_skill_executions e join app.ai_skill_definitions s on s.id=e.skill_id where e.id=$1 for update`,[id]);const row=execution.rows[0];if(!row)throw Object.assign(new Error('AI skill execution not found'),{statusCode:404});if(row.status!=='pending_approval')throw Object.assign(new Error('AI skill execution is not waiting for approval'),{statusCode:409});ensurePermissions(user,row.required_permissions);const saved=await client.query(`update app.ai_skill_executions set status='running' where id=$1 returning *`,[id]);await recordAudit(client,{actorUserId:user.id,action:'ai_skill.execution.approved',entityType:'ai_skill_execution',entityId:id,correlationId:cid});return saved.rows[0]})});
}
