'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api';
import { useAuth } from '../auth/auth-provider';

type DispatchOrder={id:string;status:string;origin:string|null;destination:string|null;vehicle_description:string|null;customer_price_cents:number|string;carrier_pay_cents:number|string;carrier_id:string|null;carrier_name:string|null;first_name?:string;last_name?:string;authority_status?:string;insurance_status?:string;internal_approval?:string;risk_level?:string};
type Carrier={id:string;legal_name:string;authority_status:string;insurance_status:string;internal_approval:string;risk_level:string};
const nextStatus:Record<string,string|null>={booked:'sourcing',sourcing:null,carrier_selected:'pickup_scheduled',pickup_scheduled:'picked_up',picked_up:'in_transit',in_transit:'delivered',delivered:'settled',settled:null,cancelled:null};
const usd=(v:number|string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)/100);
const eligible=(c:Carrier)=>c.authority_status==='active'&&c.insurance_status==='verified'&&c.internal_approval==='approved'&&c.risk_level!=='high';

export function DispatchView(){
  const {user}=useAuth();const [orders,setOrders]=useState<DispatchOrder[]>([]);const [carriers,setCarriers]=useState<Carrier[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setError('');try{const [o,c]=await Promise.all([apiRequest<DispatchOrder[]>('/v1/dispatch'),apiRequest<Carrier[]>('/v1/carriers')]);setOrders(o);setCarriers(c)}catch(reason){setError(reason instanceof Error?reason.message:'Dispatch failed')}}
  useEffect(()=>{void load()},[]);
  async function assign(event:FormEvent<HTMLFormElement>,orderId:string){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await apiRequest(`/v1/dispatch/${orderId}/assign`,{method:'POST',body:JSON.stringify({carrierId:String(form.get('carrierId')),carrierPayCents:Math.round(Number(form.get('carrierPay'))*100)})});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Carrier assignment failed')}finally{setBusy(false)}}
  async function transition(orderId:string,status:string){setBusy(true);setError('');try{await apiRequest(`/v1/orders/${orderId}/status`,{method:'POST',body:JSON.stringify({status})});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Status update failed')}finally{setBusy(false)}}
  async function unassign(orderId:string){setBusy(true);setError('');try{await apiRequest(`/v1/dispatch/${orderId}/unassign`,{method:'POST'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Carrier unassignment failed')}finally{setBusy(false)}}
  const canManage=user?.permissions.includes('dispatch.manage'); const available=carriers.filter(eligible);
  return <main className="page"><div className="page-header"><div><h1>Dispatch</h1><p>Carrier assignment is controlled here. Ineligible carriers cannot be assigned, and historical assignment is locked after pickup.</p></div><button className="icon-button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="error-state">{error}</div>:null}
    <section className="panel"><div className="panel-head"><h2>Active Shipment Board</h2><span>{orders.length} active orders · {available.length} eligible carriers</span></div>{orders.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Route / Vehicle</th><th>Economics</th><th>Carrier</th><th>Status</th><th>Dispatch Action</th></tr></thead><tbody>{orders.map(order=>{const next=nextStatus[order.status];return <tr key={order.id}><td>{order.first_name} {order.last_name}<br/><small>{order.id.slice(0,8)}</small></td><td>{order.origin??'—'} → {order.destination??'—'}<br/><small>{order.vehicle_description??'—'}</small></td><td>{usd(order.customer_price_cents)} customer<br/><small>{usd(order.carrier_pay_cents)} carrier</small></td><td>{order.carrier_name??'Unassigned'}{order.carrier_id?<><br/><small>{order.authority_status} · {order.insurance_status} · {order.internal_approval} · {order.risk_level}</small></>:null}</td><td><span className="badge">{order.status}</span></td><td>{canManage&&!order.carrier_id&&!['picked_up','in_transit','delivered','settled','cancelled'].includes(order.status)?<form onSubmit={(event)=>void assign(event,order.id)} style={{display:'flex',gap:6,alignItems:'center'}}><select name="carrierId" required defaultValue="" style={{maxWidth:180,padding:7,border:'1px solid var(--carlog-border)',borderRadius:8}}><option value="" disabled>Eligible carrier</option>{available.map(carrier=><option key={carrier.id} value={carrier.id}>{carrier.legal_name}</option>)}</select><input name="carrierPay" required type="number" min="0.01" step="0.01" placeholder="Carrier pay" style={{width:105,padding:7,border:'1px solid var(--carlog-border)',borderRadius:8}}/><button className="icon-button" disabled={busy}>Assign</button></form>:null}{canManage&&order.carrier_id&&!['picked_up','in_transit','delivered','settled','cancelled'].includes(order.status)?<button className="icon-button" disabled={busy} onClick={()=>void unassign(order.id)}>Unassign</button>:null}{canManage&&next&&!(next==='sourcing'&&order.status==='booked')?<button className="icon-button" disabled={busy} onClick={()=>void transition(order.id,next)}>{next.replaceAll('_',' ')}</button>:null}{canManage&&order.status==='booked'?<button className="icon-button" disabled={busy} onClick={()=>void transition(order.id,'sourcing')}>Start sourcing</button>:null}</td></tr>})}</tbody></table></div>:<div className="empty-state">No active orders.</div>}</section>
  </main>;
}
