import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { authorize } from '../../auth/authorize.js';
import { query,transaction } from '../../lib/database.js';
import { recordAudit } from '../../lib/audit.js';
import { enqueueDomainEvent } from '../../lib/domain-events.js';
import { requestCorrelationId } from '../../lib/request-context.js';
import { createSignedDownload,createSignedUpload } from '../../lib/storage.js';

const uuid=z.string().uuid();const slug=z.string().trim().regex(/^\/[a-z0-9/_-]*$/).max(500);
export async function registerCmsRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/public/cms/page',async request=>{const path=slug.parse((request.query as{path?:string}).path??'/');const pages=await query<{id:string;slug:string;title:string;seo_title:string|null;meta_description:string|null;published_version:number|null;content:unknown}>(`select p.id,p.slug,p.title,p.seo_title,p.meta_description,p.published_version,v.content from app.cms_pages p join app.cms_page_versions v on v.page_id=p.id and v.version=p.published_version where p.slug=$1 and p.status='published'`,[path]);if(!pages[0])throw Object.assign(new Error('Page not found'),{statusCode:404});return pages[0]});
  app.get('/v1/public/cms/navigation',async()=>query(`select label,href,sort_order,parent_id from app.cms_navigation_items where visible=true order by location,sort_order,id`));

  app.get('/v1/cms/pages',async request=>{await authorize(request,'cms.read');return query(`select p.*,(select max(version) from app.cms_page_versions v where v.page_id=p.id) latest_version from app.cms_pages p order by p.updated_at desc`)});
  app.get('/v1/cms/pages/:id',async request=>{await authorize(request,'cms.read');const id=uuid.parse((request.params as{id:string}).id);const page=(await query(`select * from app.cms_pages where id=$1`,[id]))[0];if(!page)throw Object.assign(new Error('Page not found'),{statusCode:404});const versions=await query(`select * from app.cms_page_versions where page_id=$1 order by version desc`,[id]);return{page,versions}});
  app.post('/v1/cms/pages',async(request,reply)=>{const user=await authorize(request,'cms.edit');const body=z.object({slug,title:z.string().min(1).max(250),seoTitle:z.string().max(300).nullable().optional(),metaDescription:z.string().max(500).nullable().optional(),content:z.record(z.string(),z.unknown())}).parse(request.body);const cid=requestCorrelationId(request);const result=await transaction(async client=>{const page=await client.query<{id:string}>(`insert into app.cms_pages(slug,title,status,seo_title,meta_description,created_by,updated_by) values($1,$2,'draft',$3,$4,$5,$5) returning *`,[body.slug,body.title,body.seoTitle??null,body.metaDescription??null,user.id]);const id=page.rows[0]!.id;await client.query(`insert into app.cms_page_versions(page_id,version,content,created_by) values($1,1,$2::jsonb,$3)`,[id,JSON.stringify(body.content),user.id]);await recordAudit(client,{actorUserId:user.id,action:'cms.page.created',entityType:'cms_page',entityId:id,after:page.rows[0],correlationId:cid});return page.rows[0]});return reply.code(201).send(result)});
  app.put('/v1/cms/pages/:id',async request=>{const user=await authorize(request,'cms.edit');const id=uuid.parse((request.params as{id:string}).id);const body=z.object({title:z.string().min(1).max(250),slug,seoTitle:z.string().max(300).nullable().optional(),metaDescription:z.string().max(500).nullable().optional(),content:z.record(z.string(),z.unknown())}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{const before=await client.query(`select * from app.cms_pages where id=$1 for update`,[id]);if(!before.rows[0])throw Object.assign(new Error('Page not found'),{statusCode:404});const version=await client.query<{version:number}>(`select coalesce(max(version),0)+1 version from app.cms_page_versions where page_id=$1`,[id]);await client.query(`insert into app.cms_page_versions(page_id,version,content,created_by) values($1,$2,$3::jsonb,$4)`,[id,version.rows[0]!.version,JSON.stringify(body.content),user.id]);const saved=await client.query(`update app.cms_pages set title=$2,slug=$3,seo_title=$4,meta_description=$5,status=case when status='published' then 'review' else status end,updated_by=$6,updated_at=now() where id=$1 returning *`,[id,body.title,body.slug,body.seoTitle??null,body.metaDescription??null,user.id]);await recordAudit(client,{actorUserId:user.id,action:'cms.page.updated',entityType:'cms_page',entityId:id,before:before.rows[0],after:saved.rows[0],correlationId:cid,metadata:{version:version.rows[0]!.version}});return{...saved.rows[0] as object,version:version.rows[0]!.version}})});
  app.post('/v1/cms/pages/:id/publish',async request=>{const user=await authorize(request,'cms.publish');const id=uuid.parse((request.params as{id:string}).id);const cid=requestCorrelationId(request);return transaction(async client=>{const version=await client.query<{version:number}>(`select max(version) version from app.cms_page_versions where page_id=$1`,[id]);if(!version.rows[0]?.version)throw Object.assign(new Error('Page has no content version'),{statusCode:409});const page=await client.query(`update app.cms_pages set status='published',published_version=$2,published_at=now(),updated_by=$3,updated_at=now() where id=$1 returning *`,[id,version.rows[0].version,user.id]);if(!page.rows[0])throw Object.assign(new Error('Page not found'),{statusCode:404});await enqueueDomainEvent(client,{type:'cms.page.published',source:'cms',correlationId:cid,idempotencyKey:`cms.page.published:${id}:${version.rows[0].version}`,actorUserId:user.id,payload:{pageId:id,version:version.rows[0].version}});await recordAudit(client,{actorUserId:user.id,action:'cms.page.published',entityType:'cms_page',entityId:id,after:page.rows[0],correlationId:cid});return page.rows[0]})});

  app.get('/v1/cms/navigation',async request=>{await authorize(request,'cms.read');return query(`select * from app.cms_navigation_items order by location,sort_order,id`)});
  app.put('/v1/cms/navigation',async request=>{const user=await authorize(request,'cms.edit');const body=z.object({items:z.array(z.object({id:uuid.optional(),location:z.string().max(80).default('primary'),label:z.string().min(1).max(120),href:z.string().min(1).max(1000),sortOrder:z.number().int().min(0).max(10000),visible:z.boolean().default(true),parentId:uuid.nullable().optional()})).max(200)}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{await client.query(`delete from app.cms_navigation_items`);for(const item of body.items)await client.query(`insert into app.cms_navigation_items(id,location,label,href,sort_order,visible,parent_id,created_by,updated_by) values(coalesce($1::uuid,gen_random_uuid()),$2,$3,$4,$5,$6,$7,$8,$8)`,[item.id??null,item.location,item.label,item.href,item.sortOrder,item.visible,item.parentId??null,user.id]);await recordAudit(client,{actorUserId:user.id,action:'cms.navigation.updated',entityType:'cms_navigation',entityId:'primary',after:body.items,correlationId:cid});return query(`select * from app.cms_navigation_items order by location,sort_order,id`)})});

  app.get('/v1/cms/media',async request=>{await authorize(request,'cms.read');return query(`select * from app.cms_media order by created_at desc limit 500`)});
  app.post('/v1/cms/media/upload',async request=>{const user=await authorize(request,'cms.edit');const body=z.object({name:z.string().min(1).max(255),mimeType:z.string().min(1).max(150),sizeBytes:z.number().int().min(0).max(52_428_800),altText:z.string().max(500).nullable().optional()}).parse(request.body);const id=crypto.randomUUID();const safe=body.name.replace(/[^A-Za-z0-9._-]+/g,'-');const path=`media/${id}/${safe}`;const signed=await createSignedUpload('carlog-cms-media',path);const cid=requestCorrelationId(request);await transaction(async client=>{await client.query(`insert into app.cms_media(id,name,storage_path,mime_type,size_bytes,alt_text,uploaded_by) values($1,$2,$3,$4,$5,$6,$7)`,[id,body.name,path,body.mimeType,body.sizeBytes,body.altText??null,user.id]);await recordAudit(client,{actorUserId:user.id,action:'cms.media.upload.created',entityType:'cms_media',entityId:id,after:{name:body.name,path},correlationId:cid})});return{id,...signed}});
  app.get('/v1/cms/media/:id/url',async request=>{await authorize(request,'cms.read');const id=uuid.parse((request.params as{id:string}).id);const media=(await query<{storage_path:string}>(`select storage_path from app.cms_media where id=$1`,[id]))[0];if(!media)throw Object.assign(new Error('Media not found'),{statusCode:404});return{url:await createSignedDownload('carlog-cms-media',media.storage_path,900)}});

  app.get('/v1/cms/forms',async request=>{await authorize(request,'cms.read');return query(`select * from app.cms_forms order by name`)});
}
