import { AiSkillRuntime,HttpAiModelGateway,type AiSkillDefinition,type AiTool,type AiToolContext,type JsonSchema } from '@carlog/ai-skills';
import type { PermissionKey,UserIdentity } from '@carlog/auth';
import type { IntegrationCapability,IntegrationProviderKey } from '@carlog/integrations';
import { transaction } from './database.js';

const workerId=`ai-${process.pid}-${crypto.randomUUID()}`;
type ExecutionRow={id:string;skill_id:string;skill_version:number;user_id:string;correlation_id:string;status:string;input:Record<string,unknown>;output:Record<string,unknown>|null;pending_tool_calls:Array<{toolKey:string;input:unknown}>;tool_calls:Array<{toolKey:string;allowed:boolean;at:string}>;approved_at:string|null;locked_at:string|null};
type SkillRow={id:string;key:string;name:string;description:string;category:string;version:number;status:'draft'|'active'|'disabled';input_schema:JsonSchema;output_schema:JsonSchema;instructions:string;required_permissions:PermissionKey[];approval_policy:'manual'|'supervised'|'automatic';timeout_ms:number;max_attempts:number;metadata:Record<string,unknown>};
function object(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function string(value:unknown):string|null{return typeof value==='string'?value:null}
async function identity(userId:string):Promise<UserIdentity>{return transaction(async client=>{const rows=await client.query<{id:string;email:string;display_name:string;status:string;roles:string[];permissions:PermissionKey[]}>(`select u.id,u.email,u.display_name,u.status,coalesce(array_agg(distinct r.key) filter(where r.key is not null),'{}') roles,coalesce(array_agg(distinct p.key) filter(where p.key is not null),'{}') permissions from app.users u left join app.user_roles ur on ur.user_id=u.id left join app.roles r on r.id=ur.role_id left join app.role_permissions rp on rp.role_id=r.id left join app.permissions p on p.id=rp.permission_id where u.id=$1 group by u.id`,[userId]);const row=rows.rows[0];if(!row||row.status!=='active')throw new Error('AI execution user is unavailable');return{id:row.id,email:row.email,displayName:row.display_name,active:true,roleKeys:row.roles,permissions:row.permissions}})}
function delivery(channel:string):{provider:IntegrationProviderKey;capability:IntegrationCapability;operation:string}|null{if(channel==='dialpad_sms')return{provider:'dialpad',capability:'telephony.sms',operation:'send_sms'};if(channel==='instagram')return{provider:'instagram',capability:'messaging',operation:'send_message'};if(channel==='facebook')return{provider:'facebook',capability:'messaging',operation:'send_message'};if(channel==='tiktok')return{provider:'tiktok',capability:'messaging',operation:'send_message'};return null}
function tool(key:string,permission:PermissionKey):AiTool|null{
  if(key==='crm.lead.update')return{key,requiredPermission:permission,execute:async(input:unknown,_context:AiToolContext)=>{const value=object(input);const leadId=string(value.leadId);if(!leadId)throw new Error('crm.lead.update requires leadId');await transaction(async client=>{await client.query(`update app.leads set status=coalesce($2,status),assigned_user_id=coalesce($3::uuid,assigned_user_id),updated_at=now() where id=$1`,[leadId,string(value.status),string(value.assignedUserId)])});return{leadId}}};
  if(key==='operations.task.create')return{key,requiredPermission:permission,execute:async(input:unknown,context:AiToolContext)=>{const value=object(input);const title=string(value.title);if(!title)throw new Error('operations.task.create requires title');return transaction(async client=>{const row=await client.query<{id:string}>(`insert into app.tasks(title,description,priority,assigned_user_id,lead_id,quote_id,order_id,conversation_id,due_at,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id`,[title,string(value.description),string(value.priority)??'normal',string(value.assignedUserId),string(value.leadId),string(value.quoteId),string(value.orderId),string(value.conversationId),string(value.dueAt),context.user.id]);return{taskId:row.rows[0]!.id}})}};
  if(key==='communication.message.queue')return{key,requiredPermission:permission,execute:async(input:unknown,context:AiToolContext)=>{const value=object(input);const conversationId=string(value.conversationId);const body=string(value.body);if(!conversationId||!body)throw new Error('communication.message.queue requires conversationId and body');return transaction(async client=>{const conversation=await client.query<{channel:string;provider:string;contact_id:string|null}>(`select channel,provider,contact_id from app.conversations where id=$1`,[conversationId]);const row=conversation.rows[0];if(!row)throw new Error('Conversation not found');const target=delivery(row.channel);let connectionId:string|null=null;if(target){const connection=await client.query<{id:string}>(`select ic.id from app.integration_connections ic join app.integration_capabilities cp on cp.connection_id=ic.id and cp.capability=$2 and cp.authorized=true where ic.provider=$1 and ic.status='connected' limit 1`,[target.provider,target.capability]);if(!connection.rows[0])throw new Error(`${target.provider} is not connected`);connectionId=connection.rows[0].id}const message=await client.query<{id:string}>(`insert into app.messages(conversation_id,provider,direction,sender_user_id,body,status,occurred_at) values($1,$2,'outbound',$3,$4,$5,now()) returning id`,[conversationId,row.provider,context.user.id,body,target?'queued':'sent']);if(target)await client.query(`insert into app.integration_actions(connection_id,provider,capability,operation,payload,idempotency_key,correlation_id,status) values($1,$2,$3,$4,$5::jsonb,$6,$7,'pending') on conflict(idempotency_key) do nothing`,[connectionId,target.provider,target.capability,target.operation,JSON.stringify({conversationId,messageId:message.rows[0]!.id,body,contactId:row.contact_id}),`ai:${context.executionId}:${message.rows[0]!.id}`,context.correlationId]);return{messageId:message.rows[0]!.id,status:target?'queued':'sent'}})}};
  return null;
}
async function claim():Promise<{execution:ExecutionRow;skill:SkillRow;tools:Array<{tool_key:string;required_permission:PermissionKey}>}|null>{return transaction(async client=>{const rows=await client.query<ExecutionRow>(`select * from app.ai_skill_executions where status='running' and (locked_at is null or locked_at<now()-interval '5 minutes') order by started_at for update skip locked limit 1`);const execution=rows.rows[0];if(!execution)return null;await client.query(`update app.ai_skill_executions set locked_at=now(),locked_by=$2 where id=$1`,[execution.id,workerId]);const skills=await client.query<SkillRow>(`select * from app.ai_skill_definitions where id=$1 and version=$2`,[execution.skill_id,execution.skill_version]);const skill=skills.rows[0];if(!skill)throw new Error('AI skill definition version is missing');const tools=await client.query<{tool_key:string;required_permission:PermissionKey}>(`select tool_key,required_permission from app.ai_skill_tools where skill_id=$1`,[skill.id]);return{execution,skill,tools:tools.rows}})}
export async function processOneAiSkill():Promise<boolean>{let claimed:null|{execution:ExecutionRow;skill:SkillRow;tools:Array<{tool_key:string;required_permission:PermissionKey}>}=null;try{claimed=await claim();if(!claimed)return false;const user=await identity(claimed.execution.user_id);const endpoint=process.env.AI_MODEL_GATEWAY_URL;if(!endpoint)throw new Error('AI_MODEL_GATEWAY_URL is not configured');const definition:AiSkillDefinition={id:claimed.skill.id,key:claimed.skill.key,name:claimed.skill.name,description:claimed.skill.description,category:claimed.skill.category,version:claimed.skill.version,status:claimed.skill.status,inputSchema:claimed.skill.input_schema,outputSchema:claimed.skill.output_schema,instructions:claimed.skill.instructions,toolKeys:claimed.tools.map(item=>item.tool_key),requiredPermissions:claimed.skill.required_permissions,approvalPolicy:claimed.skill.approval_policy,timeoutMs:claimed.skill.timeout_ms,maxAttempts:claimed.skill.max_attempts,metadata:claimed.skill.metadata};const runtime=new AiSkillRuntime(new HttpAiModelGateway(endpoint,process.env.AI_MODEL_GATEWAY_TOKEN??null));runtime.registerSkill(definition);for(const item of claimed.tools){const available=tool(item.tool_key,item.required_permission);if(available)runtime.registerTool(available)}const resuming=claimed.execution.pending_tool_calls.length>0&&claimed.execution.output!==null&&claimed.execution.approved_at!==null;const result=await runtime.execute({skillKey:definition.key,payload:claimed.execution.input,user,correlationId:claimed.execution.correlation_id,approved:claimed.execution.approved_at!==null,executionId:claimed.execution.id,...(resuming?{resume:{output:claimed.execution.output!,toolCalls:claimed.execution.pending_tool_calls}}:{})});await transaction(async client=>{await client.query(`update app.ai_skill_executions set status=$2,output=$3::jsonb,pending_tool_calls=$4::jsonb,tool_calls=$5::jsonb,error=$6,completed_at=$7,locked_at=null,locked_by=null where id=$1`,[claimed!.execution.id,result.status,JSON.stringify(result.output),JSON.stringify(result.pendingToolCalls),JSON.stringify(result.toolCalls),result.error,result.completedAt])});return true}catch(error){if(claimed){const message=error instanceof Error?error.message:'Unknown AI worker failure';await transaction(async client=>{await client.query(`update app.ai_skill_executions set status='failed',error=$2,completed_at=now(),locked_at=null,locked_by=null where id=$1`,[claimed!.execution.id,message])})}return Boolean(claimed)}}
