import { evaluateConditions,type AutomationAction,type AutomationDefinition } from '@carlog/automation';
import { createDomainEvent,type DomainEvent } from '@carlog/events';
import { PROVIDER_CAPABILITIES,type IntegrationCapability,type IntegrationProviderKey } from '@carlog/integrations';
import { transaction } from './database.js';

type ExecutionRow={id:string;definition_id:string;definition_version:number;correlation_id:string;status:string;current_action_id:string|null;current_action_index:number;context:Record<string,unknown>;attempts:number;approved_by:string|null;approved_at:string|null;definition:AutomationDefinition};
function object(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function string(value:unknown):string|null{return typeof value==='string'?value:null}
function eventFor(row:ExecutionRow):DomainEvent<Record<string,unknown>>{const saved=object(row.context.event);if(saved.id&&saved.type)return saved as unknown as DomainEvent<Record<string,unknown>>;return createDomainEvent({id:`manual:${row.id}`,type:'automation.manual',actorId:string(row.context.requestedBy),correlationId:row.correlation_id,payload:row.context,source:'automation',idempotencyKey:`automation.manual:${row.id}`})}
function selectedActions(definition:AutomationDefinition,event:DomainEvent<Record<string,unknown>>):AutomationAction[]{for(const branch of definition.branches??[])if(evaluateConditions(branch.conditions,event))return branch.actions;return evaluateConditions(definition.conditions,event)?definition.thenActions:definition.elseActions}
async function log(client:import('pg').PoolClient,id:string,level:'info'|'error',message:string,actionId?:string):Promise<void>{await client.query(`update app.automation_executions set logs=logs||$2::jsonb where id=$1`,[id,JSON.stringify([{at:new Date().toISOString(),level,message,...(actionId?{actionId}:{})}])])}
function delivery(channel:string):{provider:IntegrationProviderKey;capability:IntegrationCapability;operation:string}|null{if(channel==='dialpad_sms')return{provider:'dialpad',capability:'telephony.sms',operation:'send_sms'};if(channel==='instagram')return{provider:'instagram',capability:'messaging',operation:'send_message'};if(channel==='facebook')return{provider:'facebook',capability:'messaging',operation:'send_message'};if(channel==='tiktok')return{provider:'tiktok',capability:'messaging',operation:'send_message'};return null}
async function executeAction(client:import('pg').PoolClient,row:ExecutionRow,event:DomainEvent<Record<string,unknown>>,action:AutomationAction):Promise<'continue'|'pause'>{const input=action.input;const payload=object(event.payload);
  if(action.type==='wait'){const seconds=typeof input.seconds==='number'?Math.max(0,Math.min(input.seconds,2_592_000)):0;await client.query(`update app.automation_executions set status='waiting',resume_at=now()+make_interval(secs=>$2),current_action_index=current_action_index+1,current_action_id=null,attempts=0 where id=$1`,[row.id,seconds]);await log(client,row.id,'info',`Waiting ${seconds} seconds`,action.id);return'pause'}
  if(action.type==='create.task'){const title=string(input.title)??'Automation task';const leadId=string(input.leadId)??string(payload.leadId);const quoteId=string(input.quoteId)??string(payload.quoteId);const orderId=string(input.orderId)??string(payload.orderId);const conversationId=string(input.conversationId)??string(payload.conversationId);await client.query(`insert into app.tasks(title,description,priority,assigned_user_id,lead_id,quote_id,order_id,conversation_id,due_at,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[title,string(input.description),string(input.priority)??'normal',string(input.assignedUserId),leadId,quoteId,orderId,conversationId,string(input.dueAt),event.actorId]);return'continue'}
  if(action.type==='update.lead'){const leadId=string(input.leadId)??string(payload.leadId);if(!leadId)throw new Error('update.lead requires leadId');const status=string(input.status);const assigned=string(input.assignedUserId);await client.query(`update app.leads set status=coalesce($2,status),assigned_user_id=coalesce($3::uuid,assigned_user_id),updated_at=now() where id=$1`,[leadId,status,assigned]);return'continue'}
  if(action.type==='send.message'){const conversationId=string(input.conversationId)??string(payload.conversationId);const body=string(input.body);if(!conversationId||!body)throw new Error('send.message requires conversationId and body');const conversation=await client.query<{channel:string;provider:string;contact_id:string|null}>(`select channel,provider,contact_id from app.conversations where id=$1`,[conversationId]);const current=conversation.rows[0];if(!current)throw new Error('Conversation not found');const target=delivery(current.channel);let connectionId:string|null=null;if(target){const connection=await client.query<{id:string}>(`select ic.id from app.integration_connections ic join app.integration_capabilities cp on cp.connection_id=ic.id and cp.capability=$2 and cp.authorized=true where ic.provider=$1 and ic.status='connected' limit 1`,[target.provider,target.capability]);if(!connection.rows[0])throw new Error(`${target.provider} is not connected`);connectionId=connection.rows[0].id}const message=await client.query<{id:string}>(`insert into app.messages(conversation_id,provider,direction,body,status,occurred_at) values($1,$2,'outbound',$3,$4,now()) returning id`,[conversationId,current.provider,body,target?'queued':'sent']);if(target)await client.query(`insert into app.integration_actions(connection_id,provider,capability,operation,payload,idempotency_key,correlation_id,status) values($1,$2,$3,$4,$5::jsonb,$6,$7,'pending') on conflict(idempotency_key) do nothing`,[connectionId,target.provider,target.capability,target.operation,JSON.stringify({conversationId,messageId:message.rows[0]!.id,body,contactId:current.contact_id}),`automation:${row.id}:${action.id}`,row.correlation_id]);return'continue'}
  if(action.type==='integration.action'){const provider=string(input.provider) as IntegrationProviderKey|null;const capability=string(input.capability) as IntegrationCapability|null;const operation=string(input.operation);if(!provider||!capability||!operation||!Object.prototype.hasOwnProperty.call(PROVIDER_CAPABILITIES,provider)||!PROVIDER_CAPABILITIES[provider].includes(capability))throw new Error('Invalid integration.action configuration');const connection=await client.query<{id:string}>(`select ic.id from app.integration_connections ic join app.integration_capabilities cp on cp.connection_id=ic.id and cp.capability=$2 and cp.authorized=true where ic.provider=$1 and ic.status='connected' limit 1`,[provider,capability]);if(!connection.rows[0])throw new Error(`${provider} is not connected for ${capability}`);await client.query(`insert into app.integration_actions(connection_id,provider,capability,operation,payload,idempotency_key,correlation_id,status) values($1,$2,$3,$4,$5::jsonb,$6,$7,'pending') on conflict(idempotency_key) do nothing`,[connection.rows[0].id,provider,capability,operation,JSON.stringify(object(input.payload)),`automation:${row.id}:${action.id}`,row.correlation_id]);return'continue'}
  if(action.type==='run.ai_skill'){const skillKey=string(input.skillKey);const userId=event.actorId??row.approved_by;if(!skillKey||!userId)throw new Error('run.ai_skill requires a user-authorized execution context');const user=await client.query<{permissions:string[]}>(`select coalesce(array_agg(distinct p.key) filter(where p.key is not null),'{}') permissions from app.users u left join app.user_roles ur on ur.user_id=u.id left join app.role_permissions rp on rp.role_id=ur.role_id left join app.permissions p on p.id=rp.permission_id where u.id=$1 and u.status='active' group by u.id`,[userId]);if(!user.rows[0]?.permissions.includes('ai_skill.execute'))throw new Error('User lacks ai_skill.execute');const skill=await client.query<{id:string;version:number;approval_policy:string;required_permissions:string[]}>(`select id,version,approval_policy,required_permissions from app.ai_skill_definitions where key=$1 and status='active'`,[skillKey]);const selected=skill.rows[0];if(!selected)throw new Error('AI skill unavailable');for(const permission of selected.required_permissions)if(!user.rows[0].permissions.includes(permission))throw new Error(`User lacks ${permission}`);const status=selected.approval_policy==='manual'?'pending_approval':'running';await client.query(`insert into app.ai_skill_executions(skill_id,skill_version,user_id,correlation_id,status,input,approved_by,approved_at) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8)`,[selected.id,selected.version,userId,row.correlation_id,status,JSON.stringify(object(input.input)),selected.approval_policy==='manual'?null:userId,selected.approval_policy==='manual'?null:new Date().toISOString()]);return'continue'}
  throw new Error(`Unsupported automation action: ${action.type}`)
}

async function claim():Promise<ExecutionRow|null>{return transaction(async client=>{const rows=await client.query<ExecutionRow>(`select e.*,d.definition from app.automation_executions e join app.automation_definitions d on d.id=e.definition_id where (e.status='running' or (e.status='waiting' and e.resume_at<=now())) order by e.started_at for update of e skip locked limit 1`);const row=rows.rows[0];if(!row)return null;await client.query(`update app.automation_executions set status='running',resume_at=null where id=$1`,[row.id]);return{...row,status:'running'}})}
export async function processOneAutomation():Promise<boolean>{const row=await claim();if(!row)return false;try{await transaction(async client=>{const event=eventFor(row);const actions=selectedActions(row.definition,event);let index=row.current_action_index;while(index<actions.length){const action=actions[index]!;if(action.approvalPolicy==='manual'&&!(row.current_action_id===action.id&&row.approved_at)){await client.query(`update app.automation_executions set status='waiting_approval',current_action_id=$2,current_action_index=$3,approved_by=null,approved_at=null where id=$1`,[row.id,action.id,index]);await log(client,row.id,'info','Waiting for human approval',action.id);return}await client.query(`update app.automation_executions set current_action_id=$2,current_action_index=$3 where id=$1`,[row.id,action.id,index]);const outcome=await executeAction(client,row,event,action);if(outcome==='pause')return;index+=1;await client.query(`update app.automation_executions set current_action_index=$2,current_action_id=null,attempts=0,approved_by=null,approved_at=null where id=$1`,[row.id,index]);await log(client,row.id,'info','Action completed',action.id)}await client.query(`update app.automation_executions set status='completed',completed_at=now(),current_action_id=null,error=null where id=$1`,[row.id])});}catch(error){const message=error instanceof Error?error.message:'Unknown automation failure';await transaction(async client=>{const action=selectedActions(row.definition,eventFor(row))[row.current_action_index];const max=action?.retry?.maxAttempts??1;const delay=action?.retry?.delayMs??0;if(row.attempts+1<max){await client.query(`update app.automation_executions set status='waiting',resume_at=now()+make_interval(secs=>$2),attempts=attempts+1,error=$3 where id=$1`,[row.id,Math.ceil(delay/1000),message])}else await client.query(`update app.automation_executions set status='failed',completed_at=now(),attempts=attempts+1,error=$2 where id=$1`,[row.id,message]);await log(client,row.id,'error',message,action?.id)})}return true}
