import { transaction } from './database.js';

type EventRow={id:string;type:string;actor_user_id:string|null;correlation_id:string;causation_id:string|null;payload_version:number;payload:Record<string,unknown>;source:string;idempotency_key:string;occurred_at:string;attempts:number};
export async function processOneDomainEvent():Promise<boolean>{
  const event=await transaction(async client=>{const rows=await client.query<EventRow>(`select id,type,actor_user_id,correlation_id,causation_id,payload_version,payload,source,idempotency_key,occurred_at,attempts from app.domain_events where status='pending' and available_at<=now() order by occurred_at for update skip locked limit 1`);const row=rows.rows[0];if(!row)return null;await client.query(`update app.domain_events set status='processing',attempts=attempts+1 where id=$1`,[row.id]);return{...row,attempts:row.attempts+1}});
  if(!event)return false;
  try{
    await transaction(async client=>{const definitions=await client.query<{id:string;version:number}>(`select id,version from app.automation_definitions where status='published' and definition->'trigger'->>'type'='event' and definition->'trigger'->>'eventType'=$1`,[event.type]);for(const definition of definitions.rows){await client.query(`insert into app.automation_executions(definition_id,definition_version,trigger_event_id,correlation_id,status,context) values($1,$2,$3,$4,'running',$5::jsonb) on conflict(definition_id,trigger_event_id) where trigger_event_id is not null do nothing`,[definition.id,definition.version,event.id,event.correlation_id,JSON.stringify({event:{id:event.id,type:event.type,actorId:event.actor_user_id,correlationId:event.correlation_id,causationId:event.causation_id,payloadVersion:event.payload_version,payload:event.payload,source:event.source,idempotencyKey:event.idempotency_key,occurredAt:event.occurred_at}})])}await client.query(`update app.domain_events set status='published',published_at=now(),last_error=null where id=$1`,[event.id])});
  }catch(error){const message=error instanceof Error?error.message:'Unknown event processing failure';await transaction(async client=>{if(event.attempts<5)await client.query(`update app.domain_events set status='pending',available_at=now()+make_interval(secs=>$2),last_error=$3 where id=$1`,[event.id,Math.min(300,Math.pow(2,event.attempts)*5),message]);else await client.query(`update app.domain_events set status='dead_lettered',last_error=$2 where id=$1`,[event.id,message])})}
  return true;
}
