import type { PoolClient } from 'pg';
import { CentralDispatchAdapter,DialpadAdapter,FmcsaAdapter,NhtsaAdapter,ProviderError,type HttpTransport,type IntegrationProviderKey } from '@carlog/integrations';
import { transaction } from './database.js';

type ActionRow={id:string;connection_id:string|null;provider:IntegrationProviderKey;capability:string;operation:string;payload:Record<string,unknown>;correlation_id:string;attempts:number;secret_ref:string|null};
class FetchTransport implements HttpTransport{async request<T>(input:{method:'GET'|'POST'|'PUT'|'PATCH'|'DELETE';url:string;headers?:Record<string,string>;body?:unknown;timeoutMs?:number}):Promise<{status:number;headers:Record<string,string>;data:T}>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),input.timeoutMs??15000);try{const response=await fetch(input.url,{method:input.method,headers:input.headers,body:input.body===undefined?undefined:JSON.stringify(input.body),signal:controller.signal});const text=await response.text();let data:unknown=text;try{data=text?JSON.parse(text):null}catch{}return{status:response.status,headers:Object.fromEntries(response.headers.entries()),data:data as T}}finally{clearTimeout(timer)}}}
const http=new FetchTransport();
function envSecret(ref:string|null,provider:IntegrationProviderKey):string|null{if(ref?.startsWith('env:'))return process.env[ref.slice(4)]??null;const defaults:Partial<Record<IntegrationProviderKey,string|undefined>>={dialpad:process.env.DIALPAD_ACCESS_TOKEN,fmcsa:process.env.FMCSA_WEB_KEY,central_dispatch:process.env.CENTRAL_DISPATCH_TOKEN};return defaults[provider]??null}
function record(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function nestedCarrier(raw:unknown):Record<string,unknown>{const root=record(raw);const content=record(root.content);return record(content.carrier??root.carrier??raw)}
function text(value:unknown):string|null{return typeof value==='string'||typeof value==='number'?String(value):null}
function authority(value:unknown):'active'|'inactive'|'unknown'{const normalized=text(value)?.toUpperCase();return normalized==='Y'||normalized==='YES'||normalized==='ACTIVE'?'active':normalized==='N'||normalized==='NO'||normalized==='INACTIVE'?'inactive':'unknown'}
async function emit(client:PoolClient,type:string,correlationId:string,idempotencyKey:string,payload:Record<string,unknown>):Promise<void>{await client.query(`insert into app.domain_events(id,type,correlation_id,payload_version,payload,source,idempotency_key,occurred_at) values(gen_random_uuid(),$1,$2,1,$3::jsonb,'worker',$4,now()) on conflict(idempotency_key) do nothing`,[type,correlationId,JSON.stringify(payload),idempotencyKey])}

async function claim():Promise<ActionRow|null>{return transaction(async client=>{const rows=await client.query<ActionRow>(`select a.id,a.connection_id,a.provider,a.capability,a.operation,a.payload,a.correlation_id,a.attempts,c.secret_ref from app.integration_actions a left join app.integration_connections c on c.id=a.connection_id where a.status='pending' and a.available_at<=now() order by a.created_at for update skip locked limit 1`);const row=rows.rows[0];if(!row)return null;await client.query(`update app.integration_actions set status='processing',attempts=attempts+1 where id=$1`,[row.id]);return{...row,attempts:row.attempts+1}})}
async function complete(id:string,result:unknown):Promise<void>{await transaction(async client=>{await client.query(`update app.integration_actions set status='completed',result=$2::jsonb,completed_at=now(),last_error_code=null,last_error_message=null where id=$1`,[id,JSON.stringify(result??null)])})}
async function fail(action:ActionRow,error:unknown):Promise<void>{const retryable=error instanceof ProviderError?error.retryable:false;const code=error instanceof ProviderError?error.code:'ACTION_FAILED';const message=error instanceof Error?error.message:'Unknown integration failure';const missing=code==='MISSING_CREDENTIAL';await transaction(async client=>{if(missing){await client.query(`update app.integration_actions set status='blocked',last_error_code=$2,last_error_message=$3 where id=$1`,[action.id,code,message]);return}if(retryable&&action.attempts<5){const seconds=Math.min(900,Math.pow(2,action.attempts)*15);await client.query(`update app.integration_actions set status='pending',available_at=now()+make_interval(secs=>$2),last_error_code=$3,last_error_message=$4 where id=$1`,[action.id,seconds,code,message]);return}await client.query(`update app.integration_actions set status=case when attempts>=5 then 'dead_lettered' else 'failed' end,last_error_code=$2,last_error_message=$3 where id=$1`,[action.id,code,message])})}

async function processFmcsa(action:ActionRow,secret:string):Promise<unknown>{const payload=record(action.payload);const carrierId=text(payload.carrierId);const usdot=text(payload.usdot);if(!carrierId||!usdot)throw new ProviderError('fmcsa','INVALID_ACTION','Carrier and USDOT are required',false);const raw=await new FmcsaAdapter(http,secret).lookupByUsdot(usdot);const carrier=nestedCarrier(raw);const normalized={legalName:text(carrier.legalName??carrier.legal_name),dbaName:text(carrier.dbaName??carrier.dba_name),usdotNumber:text(carrier.dotNumber??carrier.usdotNumber??carrier.usdot),mcNumber:text(carrier.mcNumber??carrier.mc_number),allowedToOperate:text(carrier.allowedToOperate??carrier.allowed_to_operate),authorityStatus:authority(carrier.allowedToOperate??carrier.allowed_to_operate)};await transaction(async client=>{const previous=await client.query<{normalized_data:unknown}>(`select normalized_data from app.carrier_compliance_snapshots where carrier_id=$1 and provider='fmcsa' order by checked_at desc limit 1`,[carrierId]);const changed=previous.rows[0]?JSON.stringify(previous.rows[0].normalized_data)!==JSON.stringify(normalized):false;await client.query(`insert into app.carrier_compliance_snapshots(carrier_id,provider,provider_reference,factual_data,normalized_data,changed_from_previous) values($1,'fmcsa',$2,$3::jsonb,$4::jsonb,$5)`,[carrierId,usdot,JSON.stringify(raw),JSON.stringify(normalized),changed]);await client.query(`update app.carriers set legal_name=coalesce($2,legal_name),dba_name=coalesce($3,dba_name),authority_status=case when $4='unknown' then authority_status else $4 end,compliance_last_checked_at=now(),updated_at=now() where id=$1`,[carrierId,normalized.legalName,normalized.dbaName,normalized.authorityStatus]);if(changed)await emit(client,'carrier.compliance_changed',action.correlation_id,`carrier.compliance_changed:${carrierId}:${action.id}`,{carrierId,provider:'fmcsa'})});return{carrierId,normalized}}
async function processNhtsa(action:ActionRow):Promise<unknown>{const payload=record(action.payload);const vin=text(payload.vin);if(!vin)throw new ProviderError('nhtsa','INVALID_ACTION','VIN is required',false);return new NhtsaAdapter(http).decodeVin(vin,typeof payload.modelYear==='number'?payload.modelYear:undefined)}
async function processCentralDispatch(action:ActionRow,secret:string):Promise<unknown>{const adapter=new CentralDispatchAdapter(http,{token:secret});if(action.operation==='create_listing')return adapter.createListing(action.payload,{connectionId:action.connection_id??'system',correlationId:action.correlation_id,idempotencyKey:`worker:${action.id}`});if(action.operation==='create_dispatch')return adapter.createDispatch(action.payload,{connectionId:action.connection_id??'system',correlationId:action.correlation_id,idempotencyKey:`worker:${action.id}`});throw new ProviderError('central_dispatch','UNSUPPORTED_OPERATION',`Unsupported Central Dispatch operation: ${action.operation}`,false)}
async function processDialpad(action:ActionRow,secret:string):Promise<unknown>{if(action.operation!=='send_sms')throw new ProviderError('dialpad','UNSUPPORTED_OPERATION',`Unsupported Dialpad operation: ${action.operation}`,false);const payload=record(action.payload);const contactId=text(payload.contactId);let phone:string|null=null;if(contactId){const rows=await transaction(client=>client.query<{phone:string|null}>(`select phone from app.contacts where id=$1`,[contactId]));phone=rows.rows[0]?.phone??null}if(!phone)throw new ProviderError('dialpad','MISSING_RECIPIENT','Contact has no phone number',false);const result=await new DialpadAdapter(http,secret).sendSms({toNumbers:[phone],text:text(payload.body)??''},{connectionId:action.connection_id??'system',correlationId:action.correlation_id,idempotencyKey:`worker:${action.id}`});const resultRecord=record(result);const externalId=text(resultRecord.id??resultRecord.message_id);const messageId=text(payload.messageId);if(messageId)await transaction(async client=>{await client.query(`update app.messages set external_message_id=coalesce($2,external_message_id),status='sent' where id=$1`,[messageId,externalId])});return result}

async function execute(action:ActionRow):Promise<unknown>{if(action.operation==='health_check'){const secret=envSecret(action.secret_ref,action.provider);if(!secret&&action.provider!=='nhtsa'&&action.provider!=='website')throw new ProviderError(action.provider,'MISSING_CREDENTIAL',`${action.provider} credential is not configured`,false);return{configured:true,liveCheck:false,checkedAt:new Date().toISOString()}}const secret=envSecret(action.secret_ref,action.provider);if(action.provider==='fmcsa'){if(!secret)throw new ProviderError('fmcsa','MISSING_CREDENTIAL','FMCSA web key is not configured',false);return processFmcsa(action,secret)}if(action.provider==='nhtsa')return processNhtsa(action);if(action.provider==='central_dispatch'){if(!secret)throw new ProviderError('central_dispatch','MISSING_CREDENTIAL','Central Dispatch token is not configured',false);return processCentralDispatch(action,secret)}if(action.provider==='dialpad'){if(!secret)throw new ProviderError('dialpad','MISSING_CREDENTIAL','Dialpad access token is not configured',false);return processDialpad(action,secret)}throw new ProviderError(action.provider,'PROVIDER_NOT_IMPLEMENTED',`${action.provider} provider action is not implemented for ${action.operation}`,false)}

export async function processOneIntegrationAction():Promise<boolean>{const action=await claim();if(!action)return false;try{const result=await execute(action);await complete(action.id,result)}catch(error){await fail(action,error)}return true}
