'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api';
import { useAuth } from '../auth/auth-provider';

type Skill={id:string;key:string;name:string;description:string;category:string;version:number;status:string;approval_policy:string;required_permissions:string[];tools:Array<{toolKey:string;requiredPermission:string}>};
type Execution={id:string;key:string;name:string;status:string;started_at:string;completed_at:string|null;error:string|null;output:unknown;pending_tool_calls:unknown[]};

export function AiSkillsView(){
  const {user}=useAuth();const [skills,setSkills]=useState<Skill[]>([]);const [executions,setExecutions]=useState<Execution[]>([]);const [selected,setSelected]=useState('');const [input,setInput]=useState('{}');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setError('');try{const [s,e]=await Promise.all([apiRequest<Skill[]>('/v1/ai-skills'),apiRequest<Execution[]>('/v1/ai-skills/executions')]);setSkills(s);setExecutions(e);if(!selected){const active=s.find(item=>item.status==='active');if(active)setSelected(active.key)}}catch(reason){setError(reason instanceof Error?reason.message:'AI skills failed')}}
  useEffect(()=>{void load()},[]);
  async function execute(event:FormEvent){event.preventDefault();let parsed:Record<string,unknown>;try{parsed=JSON.parse(input) as Record<string,unknown>}catch{setError('Skill input must be valid JSON.');return}setBusy(true);setError('');try{await apiRequest(`/v1/ai-skills/${encodeURIComponent(selected)}/execute`,{method:'POST',body:JSON.stringify({input:parsed})});await load()}catch(reason){setError(reason instanceof Error?reason.message:'AI skill execution failed')}finally{setBusy(false)}}
  async function command(path:string){setBusy(true);setError('');try{await apiRequest(path,{method:'POST'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'AI skill action failed')}finally{setBusy(false)}}
  const canManage=user?.permissions.includes('ai_skill.manage');const canExecute=user?.permissions.includes('ai_skill.execute');const activeSkills=skills.filter(skill=>skill.status==='active');
  return <main className="page"><div className="page-header"><div><h1>AI Skills</h1><p>AI is treated as a permissioned platform resource. Skills receive explicit schemas, tools, permissions, approval policy, retries and timeout limits.</p></div><button className="icon-button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="error-state">{error}</div>:null}
    <div className="notice" style={{marginBottom:18}}>Skills cannot access arbitrary platform operations. Tool calls outside the skill allowlist or the executing user's permissions are rejected before any side effect.</div>
    {canExecute&&activeSkills.length?<form className="panel" onSubmit={execute} style={{marginBottom:18}}><div className="panel-head"><h2>Execute Skill</h2><span>Model execution requires the configured server-side AI gateway.</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 2fr auto',gap:10,padding:16}}><select value={selected} onChange={event=>setSelected(event.target.value)} style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}>{activeSkills.map(skill=><option key={skill.id} value={skill.key}>{skill.name} · v{skill.version}</option>)}</select><textarea value={input} onChange={event=>setInput(event.target.value)} style={{minHeight:80,padding:10,border:'1px solid var(--carlog-border)',borderRadius:9,fontFamily:'monospace'}}/><button className="icon-button" disabled={busy||!selected}>Execute</button></div></form>:null}
    <div className="two-column"><section className="panel"><div className="panel-head"><h2>Skill Catalog</h2><span>{skills.length} versions</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Skill</th><th>Category</th><th>Status</th><th>Approval</th><th>Permissions</th><th>Tools</th><th>Control</th></tr></thead><tbody>{skills.map(skill=><tr key={skill.id}><td><strong>{skill.name}</strong><br/><small>{skill.key} · v{skill.version}</small><br/><small>{skill.description}</small></td><td>{skill.category}</td><td><span className="badge">{skill.status}</span></td><td>{skill.approval_policy}</td><td>{skill.required_permissions?.join(', ')||'None'}</td><td>{skill.tools?.map(tool=>tool.toolKey).join(', ')||'None'}</td><td>{canManage&&skill.status!=='active'?<button className="icon-button" disabled={busy} onClick={()=>void command(`/v1/ai-skills/${skill.id}/activate`)}>Activate</button>:null}</td></tr>)}</tbody></table></div></section>
      <section className="panel"><div className="panel-head"><h2>Execution History</h2><span>{executions.length} runs</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Skill</th><th>Status</th><th>Started</th><th>Output / Error</th><th>Control</th></tr></thead><tbody>{executions.map(item=><tr key={item.id}><td>{item.name}<br/><small>{item.key}</small></td><td><span className="badge" data-tone={item.status==='completed'?'good':item.status==='failed'?'bad':item.status==='pending_approval'?'warn':undefined}>{item.status}</span></td><td>{new Date(item.started_at).toLocaleString('en-US')}</td><td>{item.error??(item.output?JSON.stringify(item.output):'—')}</td><td>{canExecute&&item.status==='pending_approval'?<button className="icon-button" disabled={busy} onClick={()=>void command(`/v1/ai-skills/executions/${item.id}/approve`)}>Approve</button>:null}</td></tr>)}</tbody></table></div></section></div>
  </main>;
}
