'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api';
import { useAuth } from '../auth/auth-provider';

type Page={id:string;slug:string;title:string;status:string;seo_title:string|null;meta_description:string|null;latest_version:number|null;published_version:number|null;updated_at:string};

export function PagesView(){
  const {user}=useAuth();const [pages,setPages]=useState<Page[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setError('');try{setPages(await apiRequest<Page[]>('/v1/cms/pages'))}catch(reason){setError(reason instanceof Error?reason.message:'CMS pages failed')}}
  useEffect(()=>{void load()},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);let content:Record<string,unknown>;try{content=JSON.parse(String(form.get('content')||'{}')) as Record<string,unknown>}catch{setBusy(false);setError('Page content must be valid JSON.');return}try{await apiRequest('/v1/cms/pages',{method:'POST',body:JSON.stringify({slug:String(form.get('slug')),title:String(form.get('title')),seoTitle:String(form.get('seoTitle')||'')||null,metaDescription:String(form.get('metaDescription')||'')||null,content})});event.currentTarget.reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:'Page creation failed')}finally{setBusy(false)}}
  async function publish(id:string){setBusy(true);setError('');try{await apiRequest(`/v1/cms/pages/${id}/publish`,{method:'POST'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Publish failed')}finally{setBusy(false)}}
  const canEdit=user?.permissions.includes('cms.edit');const canPublish=user?.permissions.includes('cms.publish');
  return <main className="page"><div className="page-header"><div><h1>Pages</h1><p>Versioned website content. Editing creates a new content version; publishing promotes an explicit version to the public website.</p></div><button className="icon-button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="error-state">{error}</div>:null}
    {canEdit?<form className="panel" onSubmit={create} style={{marginBottom:18}}><div className="panel-head"><h2>Create Page</h2><span>All public content remains English.</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 2fr',gap:10,padding:16}}><input name="slug" required placeholder="/services" pattern="/[a-z0-9/_-]*" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><input name="title" required placeholder="Page title" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><input name="seoTitle" placeholder="SEO title" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><input name="metaDescription" placeholder="Meta description" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><textarea name="content" defaultValue={'{"sections":[]}'} style={{gridColumn:'1/-1',minHeight:110,padding:10,border:'1px solid var(--carlog-border)',borderRadius:9,fontFamily:'monospace'}}/><button className="icon-button" disabled={busy}>Create Draft</button></div></form>:null}
    <section className="panel"><div className="panel-head"><h2>Content Library</h2><span>{pages.length} pages</span></div>{pages.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Page</th><th>Path</th><th>Status</th><th>Latest</th><th>Published</th><th>SEO</th><th>Updated</th><th>Control</th></tr></thead><tbody>{pages.map(page=><tr key={page.id}><td><strong>{page.title}</strong></td><td>{page.slug}</td><td><span className="badge" data-tone={page.status==='published'?'good':page.status==='review'?'warn':undefined}>{page.status}</span></td><td>v{page.latest_version??'—'}</td><td>{page.published_version?`v${page.published_version}`:'—'}</td><td>{page.seo_title??'—'}<br/><small>{page.meta_description??''}</small></td><td>{new Date(page.updated_at).toLocaleString('en-US')}</td><td>{canPublish&&page.latest_version!==page.published_version?<button className="icon-button" disabled={busy} onClick={()=>void publish(page.id)}>Publish Latest</button>:null}</td></tr>)}</tbody></table></div>:<div className="empty-state">No CMS pages yet.</div>}</section>
  </main>;
}
