import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { authorize } from '../../auth/authorize.js';
import { query, transaction } from '../../lib/database.js';
import { recordAudit } from '../../lib/audit.js';
import { requestCorrelationId } from '../../lib/request-context.js';

const uuid=z.string().uuid();
const socialProvider=z.enum(['instagram','facebook','tiktok','youtube','google_business_profile']);

export async function registerMarketingRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/marketing/content',async request=>{await authorize(request,'marketing.read');return query(`select c.*,coalesce(jsonb_agg(jsonb_build_object('id',v.id,'provider',v.provider,'approvalStatus',v.approval_status,'scheduledAt',v.scheduled_at,'publishedAt',v.published_at,'externalContentId',v.external_content_id,'payload',v.payload)) filter(where v.id is not null),'[]'::jsonb) variants from app.social_content c left join app.social_content_variants v on v.content_id=c.id group by c.id order by c.updated_at desc`)});
  app.post('/v1/marketing/content',async(request,reply)=>{const user=await authorize(request,'marketing.manage');const body=z.object({sourcePageId:uuid.nullable().optional(),title:z.string().min(1).max(250),body:z.string().max(30000).nullable().optional()}).parse(request.body);const cid=requestCorrelationId(request);const row=await transaction(async client=>{const created=await client.query(`insert into app.social_content(source_page_id,title,body,status,created_by) values($1,$2,$3,'draft',$4) returning *`,[body.sourcePageId??null,body.title,body.body??null,user.id]);const id=(created.rows[0] as{id:string}).id;await recordAudit(client,{actorUserId:user.id,action:'marketing.content.created',entityType:'social_content',entityId:id,after:created.rows[0],correlationId:cid});return created.rows[0]});return reply.code(201).send(row)});
  app.post('/v1/marketing/content/:id/variants',async(request,reply)=>{const user=await authorize(request,'marketing.manage');const contentId=uuid.parse((request.params as{id:string}).id);const body=z.object({provider:socialProvider,payload:z.record(z.string(),z.unknown())}).parse(request.body);const cid=requestCorrelationId(request);const row=await transaction(async client=>{const content=await client.query(`select id from app.social_content where id=$1`,[contentId]);if(!content.rows[0])throw Object.assign(new Error('Content not found'),{statusCode:404});const created=await client.query(`insert into app.social_content_variants(content_id,provider,payload,approval_status) values($1,$2,$3::jsonb,'pending') returning *`,[contentId,body.provider,JSON.stringify(body.payload)]);const id=(created.rows[0] as{id:string}).id;await recordAudit(client,{actorUserId:user.id,action:'marketing.variant.created',entityType:'social_content_variant',entityId:id,after:created.rows[0],correlationId:cid});return created.rows[0]});return reply.code(201).send(row)});
  app.post('/v1/marketing/variants/:id/approve',async request=>{const user=await authorize(request,'marketing.publish');const id=uuid.parse((request.params as{id:string}).id);const cid=requestCorrelationId(request);return transaction(async client=>{const before=await client.query(`select * from app.social_content_variants where id=$1 for update`,[id]);if(!before.rows[0])throw Object.assign(new Error('Content variant not found'),{statusCode:404});const saved=await client.query(`update app.social_content_variants set approval_status='approved',updated_at=now() where id=$1 returning *`,[id]);await client.query(`update app.social_content set status='approved',updated_at=now() where id=$1`,[(saved.rows[0] as{content_id:string}).content_id]);await recordAudit(client,{actorUserId:user.id,action:'marketing.variant.approved',entityType:'social_content_variant',entityId:id,before:before.rows[0],after:saved.rows[0],correlationId:cid});return saved.rows[0]})});
  app.post('/v1/marketing/variants/:id/schedule',async request=>{const user=await authorize(request,'marketing.publish');const id=uuid.parse((request.params as{id:string}).id);const body=z.object({scheduledAt:z.string().datetime()}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{const current=await client.query<{content_id:string;approval_status:string}>(`select content_id,approval_status from app.social_content_variants where id=$1 for update`,[id]);if(!current.rows[0])throw Object.assign(new Error('Content variant not found'),{statusCode:404});if(current.rows[0].approval_status!=='approved')throw Object.assign(new Error('Content variant requires approval before scheduling'),{statusCode:409});const saved=await client.query(`update app.social_content_variants set scheduled_at=$2,updated_at=now() where id=$1 returning *`,[id,body.scheduledAt]);await client.query(`update app.social_content set status='scheduled',updated_at=now() where id=$1`,[current.rows[0].content_id]);await recordAudit(client,{actorUserId:user.id,action:'marketing.variant.scheduled',entityType:'social_content_variant',entityId:id,after:saved.rows[0],correlationId:cid});return saved.rows[0]})});

  app.get('/v1/marketing/campaigns',async request=>{await authorize(request,'marketing.read');return query(`select c.*,(select count(*) from app.marketing_conversions x where x.campaign_id=c.id)::int conversions,(select coalesce(sum(value_cents),0) from app.marketing_conversions x where x.campaign_id=c.id)::bigint conversion_value_cents from app.marketing_campaigns c order by c.updated_at desc`)});
  app.get('/v1/marketing/conversions',async request=>{await authorize(request,'marketing.read');return query(`select x.*,c.name campaign_name,c.provider campaign_provider from app.marketing_conversions x left join app.marketing_campaigns c on c.id=x.campaign_id order by x.occurred_at desc limit 1000`)});
  app.get('/v1/marketing/funnel',async request=>{await authorize(request,'marketing.read');const [summary]=await query<Record<string,string>>(`select (select count(*) from app.attribution_touches)::text touches,(select count(*) from app.leads)::text leads,(select count(*) from app.leads where status='won')::text won_leads,(select count(*) from app.quotes)::text quotes,(select count(*) from app.quotes where status='accepted')::text accepted_quotes,(select count(*) from app.orders)::text orders,(select count(*) from app.orders where status in ('delivered','settled'))::text delivered_orders,(select coalesce(sum(customer_price_cents),0) from app.orders where status<>'cancelled')::text revenue_cents,(select coalesce(sum(customer_price_cents-carrier_pay_cents),0) from app.orders where status<>'cancelled')::text gross_profit_cents`);return Object.fromEntries(Object.entries(summary??{}).map(([key,value])=>[key,Number(value)]))});
}
