import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { authorize } from '../../auth/authorize.js';
import { query, transaction } from '../../lib/database.js';
import { recordAudit } from '../../lib/audit.js';
import { requestCorrelationId } from '../../lib/request-context.js';

const uuid=z.string().uuid();
const condition=z.object({path:z.string().min(1).max(300),operator:z.enum(['equals','not_equals','exists','contains','greater_than','less_than']),value:z.unknown().optional()});
const action=z.object({id:z.string().min(1).max(120),type:z.string().min(1).max(120),input:z.record(z.string(),z.unknown()).default({}),approvalPolicy:z.enum(['none','manual']).optional(),retry:z.object({maxAttempts:z.number().int().min(1).max(10),delayMs:z.number().int().min(0).max(86_400_000)}).optional(),timeoutMs:z.number().int().min(100).max(300_000).optional()});
const definition=z.object({trigger:z.object({type:z.literal('event'),eventType:z.string().min(1).max(200)}),conditions:z.array(condition).max(50).default([]),thenActions:z.array(action).max(100),elseActions:z.array(action).max(100).default([]),branches:z.array(z.object({conditions:z.array(condition).max(50),actions:z.array(action).max(100)})).max(20).optional()});

export async function registerAutomationRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/automations',async request=>{await authorize(request,'automation.read');return query(`select * from app.automation_definitions order by key,version desc`)});
  app.get('/v1/automations/executions',async request=>{await authorize(request,'automation.read');return query(`select e.*,d.key,d.name from app.automation_executions e join app.automation_definitions d on d.id=e.definition_id order by e.started_at desc limit 500`)});

  app.post('/v1/automations',async(request,reply)=>{const user=await authorize(request,'automation.manage');const body=z.object({key:z.string().regex(/^[a-z0-9_.-]+$/).max(150),name:z.string().min(1).max(200),definition}).parse(request.body);const cid=requestCorrelationId(request);const created=await transaction(async client=>{const version=await client.query<{version:number}>(`select coalesce(max(version),0)+1 as version from app.automation_definitions where key=$1`,[body.key]);const row=await client.query(`insert into app.automation_definitions(key,name,version,status,definition,created_by) values($1,$2,$3,'draft',$4::jsonb,$5) returning *`,[body.key,body.name,version.rows[0]!.version,JSON.stringify(body.definition),user.id]);const id=(row.rows[0] as{id:string}).id;await recordAudit(client,{actorUserId:user.id,action:'automation.created',entityType:'automation_definition',entityId:id,after:row.rows[0],correlationId:cid});return row.rows[0]});return reply.code(201).send(created)});

  app.post('/v1/automations/:id/publish',async request=>{const user=await authorize(request,'automation.publish');const id=uuid.parse((request.params as{id:string}).id);const cid=requestCorrelationId(request);return transaction(async client=>{const target=await client.query<{key:string}>(`select key from app.automation_definitions where id=$1 for update`,[id]);if(!target.rows[0])throw Object.assign(new Error('Automation not found'),{statusCode:404});await client.query(`update app.automation_definitions set status='disabled',updated_at=now() where key=$1 and status='published' and id<>$2`,[target.rows[0].key,id]);const row=await client.query(`update app.automation_definitions set status='published',updated_at=now() where id=$1 returning *`,[id]);await recordAudit(client,{actorUserId:user.id,action:'automation.published',entityType:'automation_definition',entityId:id,after:row.rows[0],correlationId:cid});return row.rows[0]})});

  app.post('/v1/automations/:id/run',async(request,reply)=>{const user=await authorize(request,'automation.manage');const id=uuid.parse((request.params as{id:string}).id);const input=z.object({context:z.record(z.string(),z.unknown()).default({})}).parse(request.body??{});const cid=requestCorrelationId(request);const result=await transaction(async client=>{const target=await client.query<{version:number;status:string}>(`select version,status from app.automation_definitions where id=$1`,[id]);if(!target.rows[0])throw Object.assign(new Error('Automation not found'),{statusCode:404});if(target.rows[0].status==='disabled')throw Object.assign(new Error('Automation is disabled'),{statusCode:409});const row=await client.query<{id:string}>(`insert into app.automation_executions(definition_id,definition_version,correlation_id,status,context) values($1,$2,$3,'running',$4::jsonb) returning id`,[id,target.rows[0].version,cid,JSON.stringify({...input.context,manual:true,requestedBy:user.id})]);await recordAudit(client,{actorUserId:user.id,action:'automation.execution.requested',entityType:'automation_execution',entityId:row.rows[0]!.id,correlationId:cid,metadata:{definitionId:id}});return{executionId:row.rows[0]!.id,status:'running'}});return reply.code(202).send(result)});
}
