import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { authorize } from '../../auth/authorize.js';
import { query,transaction } from '../../lib/database.js';
import { createSignedDownload,createSignedUpload } from '../../lib/storage.js';
import { recordAudit } from '../../lib/audit.js';
import { requestCorrelationId } from '../../lib/request-context.js';

const uuid=z.string().uuid();
const entitySchema=z.object({contactId:uuid.nullable().optional(),customerId:uuid.nullable().optional(),leadId:uuid.nullable().optional(),quoteId:uuid.nullable().optional(),orderId:uuid.nullable().optional(),carrierId:uuid.nullable().optional()});
export async function registerDocumentRoutes(app:FastifyInstance):Promise<void>{
  app.get('/v1/documents',async request=>{await authorize(request,'document.read');const q=request.query as Record<string,unknown>;const orderId=typeof q.orderId==='string'?q.orderId:null;const carrierId=typeof q.carrierId==='string'?q.carrierId:null;return query(`select * from app.documents where ($1::uuid is null or order_id=$1) and ($2::uuid is null or carrier_id=$2) order by created_at desc limit 500`,[orderId,carrierId])});
  app.post('/v1/documents/upload',async request=>{const user=await authorize(request,'document.manage');const body=z.object({name:z.string().min(1).max(255),documentType:z.string().min(1).max(100),mimeType:z.string().min(1).max(150),sizeBytes:z.number().int().min(0).max(26_214_400),expiresAt:z.string().datetime().nullable().optional(),entity:entitySchema}).parse(request.body);const links=Object.values(body.entity).filter(Boolean);if(links.length===0)throw Object.assign(new Error('Document must be linked to at least one entity'),{statusCode:400});const id=crypto.randomUUID();const safe=body.name.replace(/[^A-Za-z0-9._-]+/g,'-');const path=`documents/${id}/${safe}`;const signed=await createSignedUpload('carlog-documents',path);const cid=requestCorrelationId(request);await transaction(async client=>{await client.query(`insert into app.documents(id,name,document_type,storage_path,mime_type,size_bytes,contact_id,customer_id,lead_id,quote_id,order_id,carrier_id,expires_at,uploaded_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[id,body.name,body.documentType,path,body.mimeType,body.sizeBytes,body.entity.contactId??null,body.entity.customerId??null,body.entity.leadId??null,body.entity.quoteId??null,body.entity.orderId??null,body.entity.carrierId??null,body.expiresAt??null,user.id]);await recordAudit(client,{actorUserId:user.id,action:'document.upload.created',entityType:'document',entityId:id,after:{name:body.name,documentType:body.documentType,path,entity:body.entity},correlationId:cid})});return{id,...signed}});
  app.get('/v1/documents/:id/url',async request=>{await authorize(request,'document.read');const id=uuid.parse((request.params as{id:string}).id);const row=(await query<{storage_path:string}>(`select storage_path from app.documents where id=$1`,[id]))[0];if(!row)throw Object.assign(new Error('Document not found'),{statusCode:404});return{url:await createSignedDownload('carlog-documents',row.storage_path,300)}});
  app.patch('/v1/documents/:id',async request=>{const user=await authorize(request,'document.manage');const id=uuid.parse((request.params as{id:string}).id);const body=z.object({status:z.enum(['active','verified','expired','archived']).optional(),expiresAt:z.string().datetime().nullable().optional()}).parse(request.body);const cid=requestCorrelationId(request);return transaction(async client=>{const before=await client.query(`select * from app.documents where id=$1 for update`,[id]);if(!before.rows[0])throw Object.assign(new Error('Document not found'),{statusCode:404});const saved=await client.query(`update app.documents set status=coalesce($2,status),expires_at=case when $3::boolean then $4::timestamptz else expires_at end,updated_at=now() where id=$1 returning *`,[id,body.status??null,Object.prototype.hasOwnProperty.call(body,'expiresAt'),body.expiresAt??null]);await recordAudit(client,{actorUserId:user.id,action:'document.updated',entityType:'document',entityId:id,before:before.rows[0],after:saved.rows[0],correlationId:cid});return saved.rows[0]})});
}
