'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api';
import { useAuth } from '../auth/auth-provider';

type Conversation={id:string;channel:string;provider:string;status:string;first_name?:string|null;last_name?:string|null;email?:string|null;phone?:string|null;assigned_user_name?:string|null;priority:string;unread_count:number;last_activity_at:string;detected_intent?:string|null;ai_summary?:string|null};
type Timeline={conversationId:string;messages:Array<Record<string,unknown>>;calls:Array<Record<string,unknown>>};

export function InboxView(){
  const {user}=useAuth();const [items,setItems]=useState<Conversation[]>([]);const [selected,setSelected]=useState<Conversation|null>(null);const [timeline,setTimeline]=useState<Timeline|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setError('');try{const rows=await apiRequest<Conversation[]>('/v1/conversations');setItems(rows);if(selected){const fresh=rows.find(row=>row.id===selected.id)??null;setSelected(fresh);if(fresh)await open(fresh)}}catch(reason){setError(reason instanceof Error?reason.message:'Inbox failed')}}
  async function open(conversation:Conversation){setSelected(conversation);setError('');try{setTimeline(await apiRequest<Timeline>(`/v1/conversations/${conversation.id}/timeline`))}catch(reason){setError(reason instanceof Error?reason.message:'Timeline failed')}}
  useEffect(()=>{void load()},[]);
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);const body=String(form.get('message')??'').trim();if(!body)return;setBusy(true);setError('');try{await apiRequest(`/v1/conversations/${selected.id}/messages`,{method:'POST',body:JSON.stringify({body,idempotencyKey:crypto.randomUUID()})});event.currentTarget.reset();await open(selected);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Message send failed')}finally{setBusy(false)}}
  async function update(values:Record<string,unknown>){if(!selected)return;setBusy(true);setError('');try{await apiRequest(`/v1/conversations/${selected.id}`,{method:'PATCH',body:JSON.stringify(values)});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Conversation update failed')}finally{setBusy(false)}}
  const canSend=user?.permissions.includes('communication.send');const canAssign=user?.permissions.includes('communication.assign');
  return <main className="page"><div className="page-header"><div><h1>Communications</h1><p>Unified Inbox for Website Chat, Dialpad SMS/Phone, Instagram, Facebook and TikTok. Provider delivery is queued through the Integration Platform.</p></div><button className="icon-button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="error-state">{error}</div>:null}
    <div className="two-column"><section className="panel"><div className="panel-head"><h2>Inbox</h2><span>{items.length} conversations</span></div>{items.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Contact</th><th>Channel</th><th>Status</th><th>Priority</th><th>Unread</th><th>Last Activity</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>void open(item)} style={{cursor:'pointer',background:selected?.id===item.id?'#fff5ee':undefined}}><td>{[item.first_name,item.last_name].filter(Boolean).join(' ')||item.email||item.phone||'Unknown contact'}</td><td>{item.channel}</td><td><span className="badge">{item.status}</span></td><td>{item.priority}</td><td>{item.unread_count}</td><td>{new Date(item.last_activity_at).toLocaleString('en-US')}</td></tr>)}</tbody></table></div>:<div className="empty-state">No conversations yet.</div>}</section>
      <section className="panel"><div className="panel-head"><h2>{selected?`${selected.channel} conversation`:'Conversation'}</h2><span>{selected?.assigned_user_name??'Unassigned'}</span></div>{!selected?<div className="empty-state">Select a conversation.</div>:<><div style={{padding:14,display:'flex',gap:8,flexWrap:'wrap',borderBottom:'1px solid var(--carlog-border)'}}>{canAssign?<><button className="icon-button" disabled={busy} onClick={()=>void update({status:selected.status==='resolved'?'open':'resolved'})}>{selected.status==='resolved'?'Reopen':'Resolve'}</button><button className="icon-button" disabled={busy} onClick={()=>void update({priority:selected.priority==='urgent'?'normal':'urgent'})}>{selected.priority==='urgent'?'Normal priority':'Mark urgent'}</button></>:null}</div><div className="chat-body" style={{maxHeight:430}}>{timeline?.messages.map((message,index)=><div className={`chat-bubble${message.direction==='outbound'?' chat-bubble--user':''}`} key={String(message.id??index)}><strong style={{fontSize:10,textTransform:'uppercase'}}>{String(message.direction??'message')} · {String(message.provider??'')}</strong><div>{String(message.body??'')}</div><small>{message.occurred_at?new Date(String(message.occurred_at)).toLocaleString('en-US'):''}</small></div>)}{timeline?.calls.map((call,index)=><div className="chat-bubble" key={`call-${String(call.id??index)}`}><strong>Call · {String(call.state??'unknown')}</strong><div>{String(call.direction??'')} · {String(call.from_number??'')} → {String(call.to_number??'')}</div></div>)}</div>{canSend?<form className="chat-compose" onSubmit={send}><input name="message" placeholder="Reply…" autoComplete="off"/><button disabled={busy}>Send</button></form>:null}</>}</section>
    </div>
  </main>;
}
