'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api';
import { useAuth } from '../auth/auth-provider';

type Funnel=Record<string,number>;
type Content={id:string;title:string;body:string|null;status:string;updated_at:string;variants:Array<{id:string;provider:string;approvalStatus:string;scheduledAt:string|null;publishedAt:string|null;payload:Record<string,unknown>}>};
type Campaign={id:string;name:string;provider:string;status:string|null;conversions:number;conversion_value_cents:number|string};
const providers=['instagram','facebook','tiktok','youtube','google_business_profile'] as const;
const money=(v:number|string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)/100);

export function MarketingView(){
  const {user}=useAuth();const [funnel,setFunnel]=useState<Funnel>({});const [content,setContent]=useState<Content[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setError('');try{const [f,c,p]=await Promise.all([apiRequest<Funnel>('/v1/marketing/funnel'),apiRequest<Content[]>('/v1/marketing/content'),apiRequest<Campaign[]>('/v1/marketing/campaigns')]);setFunnel(f);setContent(c);setCampaigns(p)}catch(reason){setError(reason instanceof Error?reason.message:'Marketing data failed')}}
  useEffect(()=>{void load()},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{await apiRequest('/v1/marketing/content',{method:'POST',body:JSON.stringify({title:String(form.get('title')),body:String(form.get('body')||'')||null})});event.currentTarget.reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:'Content creation failed')}finally{setBusy(false)}}
  async function addVariant(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{await apiRequest(`/v1/marketing/content/${id}/variants`,{method:'POST',body:JSON.stringify({provider:String(form.get('provider')),payload:{text:String(form.get('text'))}})});event.currentTarget.reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:'Variant creation failed')}finally{setBusy(false)}}
  async function approve(id:string){setBusy(true);try{await apiRequest(`/v1/marketing/variants/${id}/approve`,{method:'POST'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Approval failed')}finally{setBusy(false)}}
  const canManage=user?.permissions.includes('marketing.manage');const canPublish=user?.permissions.includes('marketing.publish');
  const kpis=[['Touches',funnel.touches],['Leads',funnel.leads],['Won Leads',funnel.won_leads],['Accepted Quotes',funnel.accepted_quotes],['Delivered Orders',funnel.delivered_orders],['Revenue',money(funnel.revenue_cents??0)],['Gross Profit',money(funnel.gross_profit_cents??0)]];
  return <main className="page"><div className="page-header"><div><h1>Marketing</h1><p>Content distribution and multi-touch acquisition data connected to leads, orders, revenue and gross profit.</p></div><button className="icon-button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="error-state">{error}</div>:null}
    <section className="kpi-grid">{kpis.map(([label,value])=><article className="kpi" key={String(label)}><span>{label}</span><strong>{value??0}</strong></article>)}</section>
    {canManage?<form className="panel" onSubmit={create} style={{marginBottom:18}}><div className="panel-head"><h2>Create Source Content</h2><span>Publishing requires a separate approved channel variant.</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 2fr auto',gap:10,padding:16}}><input name="title" required placeholder="Content title" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><textarea name="body" placeholder="Approved source copy" style={{padding:10,border:'1px solid var(--carlog-border)',borderRadius:9}}/><button className="icon-button" disabled={busy}>Create</button></div></form>:null}
    <div className="two-column"><section className="panel"><div className="panel-head"><h2>Content Distribution</h2><span>{content.length} source items</span></div>{content.map(item=><article key={item.id} style={{padding:16,borderBottom:'1px solid var(--carlog-border)'}}><strong>{item.title}</strong> <span className="badge">{item.status}</span><p style={{color:'var(--carlog-muted)'}}>{item.body}</p>{item.variants.map(variant=><div key={variant.id} style={{display:'flex',gap:8,alignItems:'center',margin:'6px 0'}}><span className="badge">{variant.provider}</span><span>{variant.approvalStatus}</span>{canPublish&&variant.approvalStatus==='pending'?<button className="icon-button" disabled={busy} onClick={()=>void approve(variant.id)}>Approve</button>:null}</div>)}{canManage?<form onSubmit={event=>void addVariant(event,item.id)} style={{display:'grid',gridTemplateColumns:'140px 1fr auto',gap:8,marginTop:10}}><select name="provider">{providers.map(provider=><option key={provider}>{provider}</option>)}</select><input name="text" required placeholder="Channel copy"/><button className="icon-button" disabled={busy}>Add Variant</button></form>:null}</article>)}</section>
      <section className="panel"><div className="panel-head"><h2>Campaign Performance</h2><span>{campaigns.length} campaigns</span></div>{campaigns.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Campaign</th><th>Provider</th><th>Status</th><th>Conversions</th><th>Value</th></tr></thead><tbody>{campaigns.map(item=><tr key={item.id}><td>{item.name}</td><td>{item.provider}</td><td>{item.status??'—'}</td><td>{item.conversions}</td><td>{money(item.conversion_value_cents)}</td></tr>)}</tbody></table></div>:<div className="empty-state">No synchronized campaigns yet.</div>}</section></div>
  </main>;
}
